main: club.kidgames.liquid.plugin.LiquifyPlugin
version: 0.1.2
name: Liquify
description: Rich liquid templates with logic, filters, and tags
author: non_bogus
commands:
   liquify:
      description: Resolves liquify messages
      usage: /liquify [template]
  lq:
        description: Resolves liquify messages
        usage: /lq [template]
