main: club.kidgames.liquid.plugin.LiquifyPlugin
version: 0.1.2
name: Liquify
description: Liquify
author: non_bogus
commands:
  liquify:
    description: Resolves liquify messages
    usage: /liquify [template]
  lq:
    description: Resolves stuff
    usage: /lq [template]

